name = "StringRepFilter"
uuid = "bfe2832f-5600-46d7-a449-140889a58637"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
